// Supabase Configuration
// Replace these with your actual Supabase project credentials
const SUPABASE_URL = 'https://vbwmowkztjysjddrzcaf.supabase.co';
const SUPABASE_ANON_KEY = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZid21vd2t6dGp5c2pkZHJ6Y2FmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3Njk4OTQ2MTcsImV4cCI6MjA4NTQ3MDYxN30.pTRsHETzNFavyI4syuj9RhY_Pb-gUv8BARRTDDrnLTw';

// Initialize Supabase client
const supabase = window.supabase.createClient(SUPABASE_URL, SUPABASE_ANON_KEY);

// App Configuration
const APP_CONFIG = {
    currency: 'LKR',
    defaultLanguage: 'en',
    districts: [
        'Ampara', 'Anuradhapura', 'Badulla', 'Batticaloa', 'Colombo',
        'Galle', 'Gampaha', 'Hambantota', 'Jaffna', 'Kalutara',
        'Kandy', 'Kegalle', 'Kilinochchi', 'Kurunegala', 'Mannar',
        'Matale', 'Matara', 'Monaragala', 'Mullaitivu', 'Nuwara Eliya',
        'Polonnaruwa', 'Puttalam', 'Ratnapura', 'Trincomalee', 'Vavuniya'
    ]
};

// Translation strings
const translations = {
    en: {
        home: 'Home',
        products: 'Products',
        about: 'About',
        contact: 'Contact',
        cart: 'Cart',
        checkout: 'Checkout',
        addToCart: 'Add to Cart',
        buyNow: 'Buy Now',
        quantity: 'Quantity',
        subtotal: 'Subtotal',
        delivery: 'Delivery',
        total: 'Total',
        proceedToCheckout: 'Proceed to Checkout',
        placeOrder: 'Place Order',
        deliveryInfo: 'Delivery Information',
        paymentMethod: 'Payment Method',
        fullName: 'Full Name',
        phoneNumber: 'Phone Number',
        address: 'Address',
        district: 'District',
        city: 'City (Optional)',
        selectDistrict: 'Select District',
        emptyCart: 'Your cart is empty',
        orderSuccess: 'Order placed successfully!',
        orderError: 'Error placing order. Please try again.',
        loading: 'Loading',
        shopNow: 'Shop Now',
        featuredProducts: 'Featured Products',
        allCategories: 'All Categories',
        newest: 'Newest',
        priceLowToHigh: 'Price: Low to High',
        priceHighToLow: 'Price: High to Low',
        shopByCategory: 'Shop by Category',
        sendMessage: 'Send Message',
        quickLinks: 'Quick Links',
        followUs: 'Follow Us',
        premiumQualityTextiles: 'Premium Quality Textiles',
        discoverCollection: 'Discover our exclusive collection of fabrics'
    },
    si: {
        home: 'මුල් පිටුව',
        products: 'නිෂ්පාදන',
        about: 'අප ගැන',
        contact: 'සම්බන්ධ වන්න',
        cart: 'කරත්තය',
        checkout: 'ගෙවීම',
        addToCart: 'කරත්තයට එක් කරන්න',
        buyNow: 'දැන් මිලදී ගන්න',
        quantity: 'ප්‍රමාණය',
        subtotal: 'උප එකතුව',
        delivery: 'බෙදාහැරීම',
        total: 'එකතුව',
        proceedToCheckout: 'ගෙවීමට යන්න',
        placeOrder: 'ඇණවුම ස්ථාපිත කරන්න',
        deliveryInfo: 'බෙදාහැරීමේ තොරතුරු',
        paymentMethod: 'ගෙවීමේ ක්‍රමය',
        fullName: 'සම්පූර්ණ නම',
        phoneNumber: 'දුරකථන අංකය',
        address: 'ලිපිනය',
        district: 'දිස්ත්‍රික්කය',
        city: 'නගරය (අතිරේක)',
        selectDistrict: 'දිස්ත්‍රික්කය තෝරන්න',
        emptyCart: 'ඔබේ කරත්තය හිස්',
        orderSuccess: 'ඇණවුම සාර්ථකව ස්ථාපිත විය!',
        orderError: 'ඇණවුම ස්ථාපිත කිරීමේ දෝෂයකි. කරුණාකර නැවත උත්සාහ කරන්න.',
        loading: 'පූර්ණ කරමින්',
        shopNow: 'දැන් මිලදී ගන්න',
        featuredProducts: 'විශේෂාංග නිෂ්පාදන',
        allCategories: 'සියලුම වර්ග',
        newest: 'නවතම',
        priceLowToHigh: 'මිල: අඩු සිට ඉහළ',
        priceHighToLow: 'මිල: ඉහළ සිට අඩු',
        shopByCategory: 'වර්ගය අනුව මිලදී ගන්න',
        sendMessage: 'පණිවිඩය යවන්න',
        quickLinks: 'ඉක්මන් සබැඳි',
        followUs: 'අපව අනුගමනය කරන්න',
        premiumQualityTextiles: 'උසස් තත්ත්වයේ රෙදිපිළි',
        discoverCollection: 'අපගේ සුවිශේෂී රෙදිපිළි එකතුව සොයා ගන්න'
    },
    ta: {
        home: 'முகப்பு',
        products: 'தயாரிப்புகள்',
        about: 'எங்களை பற்றி',
        contact: 'தொடர்பு',
        cart: 'வண்டி',
        checkout: 'செலுத்துதல்',
        addToCart: 'வண்டியில் சேர்க்கவும்',
        buyNow: 'இப்போது வாங்கவும்',
        quantity: 'அளவு',
        subtotal: 'துணை மொத்தம்',
        delivery: 'விநியோகம்',
        total: 'மொத்தம்',
        proceedToCheckout: 'கட்டணத்திற்கு செல்லவும்',
        placeOrder: 'ஆர்டரை வைக்கவும்',
        deliveryInfo: 'விநியோக தகவல்',
        paymentMethod: 'கட்டண முறை',
        fullName: 'முழு பெயர்',
        phoneNumber: 'தொலைபேசி எண்',
        address: 'முகவரி',
        district: 'மாவட்டம்',
        city: 'நகரம் (விருப்பமானது)',
        selectDistrict: 'மாவட்டத்தைத் தேர்ந்தெடுக்கவும்',
        emptyCart: 'உங்கள் வண்டி காலியாக உள்ளது',
        orderSuccess: 'ஆர்டர் வெற்றிகரமாக வைக்கப்பட்டது!',
        orderError: 'ஆர்டரை வைப்பதில் பிழை. மீண்டும் முயற்சிக்கவும்.',
        loading: 'ஏற்றுகிறது',
        shopNow: 'இப்போது வாங்கவும்',
        featuredProducts: 'சிறப்பு தயாரிப்புகள்',
        allCategories: 'அனைத்து வகைகளும்',
        newest: 'புதியவை',
        priceLowToHigh: 'விலை: குறைந்த முதல் உயர்ந்த',
        priceHighToLow: 'விலை: உயர்ந்த முதல் குறைந்த',
        shopByCategory: 'வகைப்படி வாங்கவும்',
        sendMessage: 'செய்தியை அனுப்பவும்',
        quickLinks: 'விரைவு இணைப்புகள்',
        followUs: 'எங்களைப் பின்தொடரவும்',
        premiumQualityTextiles: 'உயர்தர துணிகள்',
        discoverCollection: 'எங்கள் பிரத்யேக துணி சேகரிப்பைக் கண்டறியவும்'
    }
};
